port: 9238
socket_dir: "/run/uwsgi/stats/"
pidfile: "/run/uwsgi_expoter.pid"
stats_sockets:

- domain: your.domain.com
  socket: your_socket_name.sock

- domain: other-domain.com
  socket: other_socket_domain.sock
