port: 9238
soket_dir: "/run/uwsgi/stats/"
pidfile: "/run/uwsgi_expoter.pid"
stats_sokets:

- domain: your.domain.com
  soket: your_soket_name.sock

- domain: other-domain.com
  soket: other_soket_domain.sock
